name: run main.py

on:
  schedule:
    - cron: '* * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: execute py script # run main.py
        run: python main.py
