name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install python packages
        run: |
          pip install -r requirements.txt
      - name: execute py script  # run main.py
        run: python main.py

